name: Run AWS Glue Cleaning Job

on:
  workflow_dispatch:   # Manual run button se trigger hoga

jobs:
  glue-job:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Start Glue Job and wait
      run: |
        echo "Starting Glue Job..."

        JOB_RUN_ID=$(aws glue start-job-run \
          --job-name liquor-sales-cleaning-job-copy \
          --query 'JobRunId' --output text)

        echo "Glue Job Run ID: $JOB_RUN_ID"

        aws glue wait job-run-complete \
          --job-name liquor-sales-cleaning-job-copy \
          --run-id $JOB_RUN_ID

        echo "Glue Job completed successfully"
